@startuml
class AttackInteraction {
    + AttackInteraction(target:Character, attack:Attack)
    + <<new>> getResult() : InteractionEnum
    + getDamage() : float
    + getAttack() : Attack
}
Interaction <|-- AttackInteraction
@enduml
