@startuml
class AttributeModifier {
    remainingTurns : int
    multiplier : float
    finished : bool
    + AttributeModifier(remainingTurns:int, attribute:AttributeEnum, multiplier:float)
    + getRemainingTurns() : int
    + getAttribute() : AttributeEnum
    + getMultiplier() : float
    + isFinished() : bool
    + decrementRemainingTurns() : void
    + setFinished(finished:bool) : void
    + turnHasPassed() : void
}
AttributeModifier --> "attribute" AttributeEnum
@enduml
