@startuml
class StatusEffect {
    + StatusEffect(name:string, target:Character, actionType:ActionType, attribute:AttributeEnum, multiplier:float, chance:float, turns:int)
    + getAttribute() : AttributeEnum
    + getMultiplier() : float
    + getChance() : float
    + getTurns() : int
}
GameAction <|-- StatusEffect
@enduml
