@startuml
class CommandHistory {
    position : int
    + Push(command_string:string) : void
    + Next() : string
    + Previous() : string
    + Clear() : void
}
class "List`1"<T> {
}
CommandHistory o-> "history<string>" "List`1"
@enduml
