@startuml
class GameScript {
    + initGameScript() : void
    positionSprites() : void
    updateHUD() : void
    OnGUI() : void
    + getPlayer() : Player
    + getOpponent() : Opponent
    + setPlayerLoaded(playerLoaded:bool) : void
    + getPlayerLoaded() : bool
    + setOpponentLoaded(opponentLoaded:bool) : void
    + getOpponentLoaded() : bool
    + getCharactersLoaded() : bool
    + isGameOver() : bool
    + hasPlayerLost() : bool
    + hasOpponentLost() : bool
    + initOpponentGameActions() : void
    + getOpponentGameActions() : List<GameAction>
    + setPlayerGameActions(playerGameActions:List<GameAction>) : void
    + getPlayerGameActions() : List<GameAction>
    + setOpponentChosen(opponentChosen:bool) : void
    + setPlayerChosen(playerChosen:bool) : void
    + getOpponentChosen() : bool
    + getPlayerChosen() : bool
    + getPlayerMethods() : MethodInfo[]
    + dealDamage(target:Character, damage:float) : void
    + heal(target:Character, healingAmount:float) : void
    + addModifier(target:Character, attributeModifier:AttributeModifier) : void
    + endTurn() : void
}
MonoBehaviour <|-- GameScript
@enduml
