@startuml
enum TerminalLogType {
    Error= LogType.Error,
    Assert= LogType.Assert,
    Warning= LogType.Warning,
    Message= LogType.Log,
    Exception= LogType.Exception,
    Input,
    ShellMessage,
}
class LogItem <<struct>> {
    + message : string
    + stack_trace : string
}
class CommandLog {
    max_items : int
    + getLogs() : List<LogItem>
    + CommandLog(max_items:int)
    + handleLog(message:string, type:TerminalLogType) : void
    + handleLog(message:string, stack_trace:string, type:TerminalLogType) : void
    + Clear() : void
}
LogItem --> "type" TerminalLogType
@enduml
